// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Message.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Message TABLE
class TableMessage extends SqfEntityTableBase {
  TableMessage() {
    // declare properties of EntityTable
    tableName = 'message';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('title', DbType.text,
          isUnique: false, isNotNull: false, isIndex: false),
      SqfEntityFieldBase('text', DbType.text,
          isUnique: false, isNotNull: false, isIndex: false),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableMessage();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence? _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class OpenZapDatabaseModel extends SqfEntityModelProvider {
  OpenZapDatabaseModel() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    databaseTables = [
      TableMessage.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Message
class Message {
  Message({this.id, this.title, this.text}) {
    _setDefaultValues();
  }
  Message.withFields(this.title, this.text) {
    _setDefaultValues();
  }
  Message.withId(this.id, this.title, this.text) {
    _setDefaultValues();
  }
  // fromMap v2.0
  Message.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['title'] != null) {
      title = o['title'].toString();
    }
    if (o['text'] != null) {
      text = o['text'].toString();
    }
  }
  // FIELDS (Message)
  int? id;
  String? title;
  String? text;

  BoolResult? saveResult;
  // end FIELDS (Message)

  static const bool _softDeleteActivated = false;
  MessageManager? __mnMessage;

  MessageManager get _mnMessage {
    return __mnMessage = __mnMessage ?? MessageManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (text != null) {
      map['text'] = text;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (text != null) {
      map['text'] = text;
    }

    return map;
  }

  /// This method returns Json String [Message]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Message]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [title, text];
  }

  List<dynamic> toArgsWithIds() {
    return [id, title, text];
  }

  static Future<List<Message>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR Message.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<Message>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Message>[];
    try {
      objList = list
          .map((message) => Message.fromMap(message as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Message.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Message>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<Message> objList = <Message>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Message.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Message by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int? id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Message if exist, otherwise returns null
  Future<Message?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    Message? obj;
    final data = await _mnMessage.getById([id]);
    if (data.length != 0) {
      obj = Message.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Message) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int?> save() async {
    if (id == null || id == 0) {
      id = await _mnMessage.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnMessage.update(this);
    }

    return id;
  }

  /// saveAs Message. Returns a new Primary Key value of Message

  /// <returns>Returns a new Primary Key value of Message
  Future<int?> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Message> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Message> messages) async {
    // final results = _mnMessage.saveAll('INSERT OR REPLACE INTO message (id,title, text)  VALUES (?,?,?)',messages);
    // return results; removed in sqfentity_gen 1.3.0+6
    await OpenZapDatabaseModel().batchStart();
    for (final obj in messages) {
      await obj.save();
    }
    //    return OpenZapDatabaseModel().batchCommit();
    final result = await OpenZapDatabaseModel().batchCommit();
    for (int i = 0; i < messages.length; i++) {
      if (messages[i].id == null) {
        messages[i].id = result![i] as int;
      }
    }

    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id

  Future<int?> upsert() async {
    try {
      final result = await _mnMessage.rawInsert(
          'INSERT OR REPLACE INTO message (id,title, text)  VALUES (?,?,?)',
          [id, title, text]);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Message id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Message id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Message Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<Message>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Message> messages) async {
    final results = await _mnMessage.rawInsertAll(
        'INSERT OR REPLACE INTO message (id,title, text)  VALUES (?,?,?)',
        messages);
    return results;
  }

  /// Deletes Message

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted

  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Message invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnMessage
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnMessage.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  MessageFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return MessageFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  MessageFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return MessageFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {}
  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion message

// region MessageField
class MessageField extends SearchCriteria {
  MessageField(this.messageFB);
  // { param = DbParameter(); }
  DbParameter param = DbParameter();
  String _waitingNot = '';
  MessageFilterBuilder messageFB;

  MessageField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  MessageFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    messageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, messageFB.parameters, param, SqlSyntax.EQuals,
            messageFB._addedBlocks)
        : setCriteria(pValue, messageFB.parameters, param, SqlSyntax.NotEQuals,
            messageFB._addedBlocks);
    _waitingNot = '';
    messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
        messageFB._addedBlocks.retVal;
    return messageFB;
  }

  MessageFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    messageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, messageFB.parameters, param,
            SqlSyntax.EQualsOrNull, messageFB._addedBlocks)
        : setCriteria(pValue, messageFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, messageFB._addedBlocks);
    _waitingNot = '';
    messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
        messageFB._addedBlocks.retVal;
    return messageFB;
  }

  MessageFilterBuilder isNull() {
    messageFB._addedBlocks = setCriteria(
        0,
        messageFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        messageFB._addedBlocks);
    _waitingNot = '';
    messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
        messageFB._addedBlocks.retVal;
    return messageFB;
  }

  MessageFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      messageFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          messageFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          messageFB._addedBlocks);
      _waitingNot = '';
      messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
          messageFB._addedBlocks.retVal;
    }
    return messageFB;
  }

  MessageFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      messageFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          messageFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          messageFB._addedBlocks);
      _waitingNot = '';
      messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
          messageFB._addedBlocks.retVal;
      messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
          messageFB._addedBlocks.retVal;
    }
    return messageFB;
  }

  MessageFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      messageFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          messageFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          messageFB._addedBlocks);
      _waitingNot = '';
      messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
          messageFB._addedBlocks.retVal;
    }
    return messageFB;
  }

  MessageFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      messageFB._addedBlocks = setCriteria(
          pFirst,
          messageFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          messageFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        messageFB._addedBlocks = setCriteria(pFirst, messageFB.parameters,
            param, SqlSyntax.LessThan, messageFB._addedBlocks);
      } else {
        messageFB._addedBlocks = setCriteria(pFirst, messageFB.parameters,
            param, SqlSyntax.GreaterThanOrEquals, messageFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        messageFB._addedBlocks = setCriteria(pLast, messageFB.parameters, param,
            SqlSyntax.GreaterThan, messageFB._addedBlocks);
      } else {
        messageFB._addedBlocks = setCriteria(pLast, messageFB.parameters, param,
            SqlSyntax.LessThanOrEquals, messageFB._addedBlocks);
      }
    }
    _waitingNot = '';
    messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
        messageFB._addedBlocks.retVal;
    return messageFB;
  }

  MessageFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    messageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, messageFB.parameters, param,
            SqlSyntax.GreaterThan, messageFB._addedBlocks)
        : setCriteria(pValue, messageFB.parameters, param,
            SqlSyntax.LessThanOrEquals, messageFB._addedBlocks);
    _waitingNot = '';
    messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
        messageFB._addedBlocks.retVal;
    return messageFB;
  }

  MessageFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    messageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, messageFB.parameters, param, SqlSyntax.LessThan,
            messageFB._addedBlocks)
        : setCriteria(pValue, messageFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, messageFB._addedBlocks);
    _waitingNot = '';
    messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
        messageFB._addedBlocks.retVal;
    return messageFB;
  }

  MessageFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    messageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, messageFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, messageFB._addedBlocks)
        : setCriteria(pValue, messageFB.parameters, param, SqlSyntax.LessThan,
            messageFB._addedBlocks);
    _waitingNot = '';
    messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
        messageFB._addedBlocks.retVal;
    return messageFB;
  }

  MessageFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    messageFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, messageFB.parameters, param,
            SqlSyntax.LessThanOrEquals, messageFB._addedBlocks)
        : setCriteria(pValue, messageFB.parameters, param,
            SqlSyntax.GreaterThan, messageFB._addedBlocks);
    _waitingNot = '';
    messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
        messageFB._addedBlocks.retVal;
    return messageFB;
  }

  MessageFilterBuilder inValues(dynamic pValue) {
    messageFB._addedBlocks = setCriteria(
        pValue,
        messageFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        messageFB._addedBlocks);
    _waitingNot = '';
    messageFB._addedBlocks.needEndBlock![messageFB._blockIndex] =
        messageFB._addedBlocks.retVal;
    return messageFB;
  }
}
// endregion MessageField

// region MessageFilterBuilder
class MessageFilterBuilder extends SearchCriteria {
  MessageFilterBuilder(Message obj) {
    whereString = '';
    groupByList = <String>[];
    _addedBlocks.needEndBlock!.add(false);
    _addedBlocks.waitingStartBlock!.add(false);
    _obj = obj;
  }
  AddedBlocks _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
  int _blockIndex = 0;
  List<DbParameter> parameters = <DbParameter>[];
  List<String> orderByList = <String>[];
  Message? _obj;
  QueryParams qparams = QueryParams();
  int _pagesize = 0;
  int _page = 0;

  /// put the sql keyword 'AND'
  MessageFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  MessageFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  MessageFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock!.add(true);
    _addedBlocks.needEndBlock!.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock![_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  MessageFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock![_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  MessageFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  MessageFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  MessageFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock![_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock!.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock!.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  MessageFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String? s in argFields as List<String?>) {
          if (s!.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  MessageFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String? s in argFields as List<String?>) {
          if (s!.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  MessageFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String? s in argFields as List<String?>) {
          if (s!.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  MessageFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String? s in argFields as List<String?>) {
          if (s!.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  MessageField setField(MessageField? field, String colName, DbType dbtype) {
    return MessageField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock![_blockIndex]);
  }

  MessageField? _id;
  MessageField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  MessageField? _title;
  MessageField get title {
    return _title = setField(_title, 'title', DbType.text);
  }

  MessageField? _text;
  MessageField get text {
    return _text = setField(_text, 'text', DbType.text);
  }

  bool _getIsDeleted = false;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text || param.value[0] is String
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName!)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName!);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value = param.value == null
                  ? null
                  : param.value == true
                      ? 1
                      : 0;
              param.value2 = param.value2 == null
                  ? null
                  : param.value2 == true
                      ? 1
                      : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Message._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<Message> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult(success: false);

    if (Message._softDeleteActivated && !hardDelete) {
      r = await _obj!._mnMessage.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj!._mnMessage.delete(qparams);
    }
    return r;
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from message ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj!._mnMessage.updateBatch(qparams, values);
  }

  /// This method always returns Message Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Message>
  Future<Message?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj!._mnMessage.toList(qparams);
    final data = await objFuture;
    Message? obj;
    if (data.isNotEmpty) {
      obj = Message.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [Message]
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c)? messageCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final messagesFuture = await _obj!._mnMessage.toList(qparams);
    final int count = messagesFuture[0]['CNT'] as int;
    if (messageCount != null) {
      messageCount(count);
    }
    return count;
  }

  /// This method returns List<Message> [Message]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Message>
  Future<List<Message>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<Message> messagesData = await Message.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return messagesData;
  }

  /// This method returns Json String [Message]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Message]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Message]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj!._mnMessage.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Message]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM message WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj!._mnMessage.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Message]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj!._mnMessage.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Message.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    _buildParameters();

    final objectFuture = _obj!._mnMessage.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion MessageFilterBuilder

// region MessageFields
class MessageFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fTitle;
  static TableField get title {
    return _fTitle =
        _fTitle ?? SqlSyntax.setField(_fTitle, 'title', DbType.text);
  }

  static TableField? _fText;
  static TableField get text {
    return _fText = _fText ?? SqlSyntax.setField(_fText, 'text', DbType.text);
  }
}
// endregion MessageFields

//region MessageManager
class MessageManager extends SqfEntityProvider {
  MessageManager()
      : super(OpenZapDatabaseModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'message';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion MessageManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await OpenZapDatabaseModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await OpenZapDatabaseModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await OpenZapDatabaseModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class OpenZapDatabaseModelSequenceManager extends SqfEntityProvider {
  OpenZapDatabaseModelSequenceManager() : super(OpenZapDatabaseModel());
}
// END OF ENTITIES
